from fastapi import APIRouter, Response
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from io import BytesIO
import datetime

router = APIRouter()

@router.get("/generate-report")
async def generate_report(medicine: str, price: float, platform: str, risk: str):
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # Title
    c.setFont("Helvetica-Bold", 24)
    c.drawCentredString(width/2, height - 50, "Medicine Price Analysis Report")
    
    c.setFont("Helvetica", 12)
    c.drawRightString(width - 50, height - 70, f"Date: {datetime.date.today()}")

    # Content
    c.line(50, height - 80, width - 50, height - 80)
    
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, height - 120, f"Medicine: {medicine}")
    
    c.setFont("Helvetica", 14)
    c.drawString(50, height - 150, f"Current Best Price: INR {price}")
    c.drawString(50, height - 175, f"Platform: {platform}")
    
    # ML Analysis
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, height - 220, "ML Intelligence Insights")
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 245, f"Stockout Risk Level: {risk}")
    c.drawString(50, height - 265, "Price Trend: Predicted to stabilize over next 7 days.")
    
    # Disclaimer
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 50, "Disclaimer: This report is generated by MediCompare ML Engine for educational purposes.")

    c.showPage()
    c.save()

    pdf_out = buffer.getvalue()
    buffer.close()

    return Response(
        content=pdf_out,
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={medicine}_Report.pdf"}
    )
